#!/usr/bin/env python3

from geometry_msgs.msg import PoseStamped, PoseWithCovarianceStamped
from nav2_simple_commander.robot_navigator import BasicNavigator
from map_simulator.srv import Spawn
from ackermann_msgs.msg import AckermannDrive
import rclpy
from rclpy.node import Node
from math import atan2


class Planner(Node):

    def __init__(self):
        super().__init__('navigator')

        self.goal_sub = self.create_subscription(PoseStamped, '/goal_pose', self.goal_cb, 10)
        # self.plan_pub = self.create_publisher(Path, 'plan_timed', 10)
        self.navigator = BasicNavigator('navigator', namespace='/zoe')

        self.reset_sub = self.create_subscription(PoseWithCovarianceStamped, '/initialpose', self.reset_cb, 10)
        self.spawner = self.create_client(Spawn, '/simulator/spawn')
        self.cmd_pub = self.create_publisher(AckermannDrive, 'cmd', 1)
        self.spawner.wait_for_service()

    def goal_cb(self, pose):
        self.navigator.getPath(PoseStamped(), pose, planner_id = 'Hybrid')

    def reset_cb(self, pose):

        req = Spawn.Request()
        req.robot_namespace = '/zoe'
        req.x = pose.pose.pose.position.x
        req.y = pose.pose.pose.position.y
        req.theta = 2*atan2(pose.pose.pose.orientation.z, pose.pose.pose.orientation.w)
        self.spawner.call_async(req)
        self.cmd_pub.publish(AckermannDrive())


rclpy.init(args=None)
node = Planner()

rclpy.spin(node)
node.destroy_node()
rclpy.shutdown()
